language: swift
osx_image: xcode9.1
podfile: Example/Podfile
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - EXAMPLE_WORKSPACE=Example/JKEmoji.xcworkspace
  - WORKSPACE=JKEmoji.xcworkspace
  - SCHEME=JKEmoji
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES TEST | xcpretty;
  - xcodebuild -workspace "$EXAMPLE_WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  - pod lib lint

